name: BatesPortfolio

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - 'feat/*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Run build for PRs
        run: |
          npm ci
          npm run build
